##################### Grafana Configuration #####################
app_mode = production
instance_name = Home Assistant

[paths]
data = /data
logs = /var/logs/grafana
plugins = /var/lib/grafana/plugins

[plugins]
allow_loading_unsigned_plugins =

[server]
protocol = http
http_addr =
http_port = 3000
domain = localhost
enforce_domain = false
root_url = %(protocol)s://%(domain)s:%(http_port)s%%ingress_entry%%
router_logging = false
static_root_path = public
enable_gzip = true
cert_file = false
cert_key = false

[database]
type = sqlite3
host = 127.0.0.1:3306
name = grafana
user = root
password =
ssl_mode = disable
ca_cert_path =
client_key_path =
client_cert_path =
server_cert_name =
path = grafana.db

[remote_cache]
type = memcached
connstr = 127.0.0.1:11211

[analytics]
reporting_enabled = true
check_for_updates = true
google_analytics_ua_id =
google_tag_manager_id =

[security]
admin_user = admin
admin_password = hassio
secret_key = SW2YcwTIb9zpOOhoPsMm
login_remember_days = 7
cookie_username = grafana_user
cookie_remember_name = grafana_remember
disable_gravatar = false
data_source_proxy_whitelist =
allow_embedding = true

[snapshots]
external_enabled = true
external_snapshot_url = https://snapshots-origin.raintank.io
external_snapshot_name = Publish to snapshot.raintank.io

[users]
allow_sign_up = false
allow_org_create = false
auto_assign_org = true
auto_assign_org_role = Admin
verify_email_enabled = false
login_hint = email or username

[auth.anonymous]
enabled = false
org_name = Main Org.
org_role = Viewer

[auth.github]
enabled = false
allow_sign_up = false
client_id = some_id
client_secret = some_secret
scopes = user:email
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
team_ids =
allowed_organizations =

[auth.google]
enabled = false
allow_sign_up = false
client_id = some_client_id
client_secret = some_client_secret
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token
allowed_domains =

[auth.basic]
enabled = true

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
whitelist = 127.0.0.1

[auth.ldap]
enabled = false
config_file = /etc/grafana/ldap.toml

[smtp]
enabled = false
host = localhost:25
user =
password =
cert_file =
key_file =
skip_verify = false
from_address = admin@grafana.localhost

[emails]
welcome_email_on_sign_up = false
templates_pattern = emails/*.html

[log]
mode = console
buffer_len = 10000
level = Info

[log.console]
level =
formatting = false

[log.file]
level =
log_rotate = true
max_lines = 1000000
max_lines_shift = 28
daily_rotate = true
max_days = 7

[log.syslog]
level =
network =
address =
facility =
tag =

[event_publisher]
enabled = false
rabbitmq_url = amqp://localhost/
exchange = grafana_events

[dashboards.json]
enabled = false
path = /var/lib/grafana/dashboards

[quota]
enabled = false
org_user = 10
org_dashboard = 100
org_data_source = 10
org_api_key = 10
user_org = 10
global_user = -1
global_org = -1
global_dashboard = -1
global_api_key = -1
global_session = -1

[live]
max_connections = 0

[unified_alerting]
enabled = true

[alerting]
enabled = false
